---
- name: put users into /etc/yubico/authorized_yubikeys
  lineinfile:
    path: /etc/yubico/authorized_yubikeys
    line: "{{ item }}:{{ yubikey_users[item].yubikey }}"
  loop: "{{ yubikey_lognames }}"

- name: create users
  user:
    name: "{{ item }}"
    comment: "{{ yubikey_users[item].name }}"
    shell: /bin/bash
  loop: "{{ yubikey_lognames }}"

- name: ensure groups
  group:
    name: "{{ item }}"
  loop: "{{ yubikey_lognames }}"

- name: ensure users in groups
  user:
    name: "{{ item }}"
    group: "{{ item }}"
  loop: "{{ yubikey_lognames }}"

- name: create .ssh dirs
  file:
    path: "/home/{{ item }}/.ssh"
    owner: "{{ item }}"
    group: "{{ item }}"
    state: directory
    mode: 0700
  loop: "{{ yubikey_lognames }}"

- name: create .ssh/authorized_keys
  copy:
    dest: "/home/{{ item }}/.ssh/authorized_keys"
    owner: "{{ item }}"
    group: "{{ item }}"
    content: "{{ yubikey_users[item].sshkey }}"
    force: no
  loop: "{{ yubikey_lognames }}"

- name: ensure ssh keys in .ssh/authorized_keys
  lineinfile:
    path: "/home/{{ item }}/.ssh/authorized_keys"
    line: "{{ yubikey_users[item].sshkey }}"
  loop: "{{ yubikey_lognames }}"

- name: Add users to group sudo
  user:
    name: "{{ item }}"
    groups: sudo
    append: yes
  loop: "{{ sudo_root_lognames }}"

- name: "Allowing 'sudo su - {{ other_sudo_user }}'"
  lineinfile:
    path: "/etc/sudoers"
    line: "{{ item }} ALL=(root) /bin/su - {{ other_sudo_user }}"
  loop: "{{ sudo_other_lognames }}"