---
- name: Install sudo
  apt:
    name: sudo
    state: latest

- name: Install libpam-yubico
  apt:
    name: libpam-yubico
    state: latest

- name: create /etc/yubico
  file:
    path: /etc/yubico
    state: directory

- name: create /etc/yubico/authorized_yubikeys
  copy:
    content: ""
    dest: /etc/yubico/authorized_yubikeys
    force: no

- name: Add Yubikey to sudo
  lineinfile:
    path: "/etc/pam.d/sudo"
    insertafter: '#%PAM-1.0'
    line: "auth sufficient pam_yubico.so authfile=/etc/yubico/authorized_yubikeys id={{ yubikey_id }} key={{ yubikey_key }}"
  when: ansible_distribution == "Debian" and ansible_distribution_major_version != '8'

- name: Set permissions on /etc/pam.d/sudo
  file:
    path: /etc/pam.d/sudo
    mode: 0600